on: [push, pull_request]

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./gradlew assembleDebug
    - run: ./gradlew lint
    - run: ./gradlew ktlint
